---
repos:
  - name: release-service
    url: https://github.com/konflux-ci/release-service
    ref: cc4d5768624a98bebbf6189999cf8b776233738a  # main
    description: Operator

  - name: internal-services
    url: https://github.com/konflux-ci/internal-services
    ref: 340ec0adb22dbd433aa4db2df03770903aa2734c  # main
    description: Internal cluster controller

  - name: release-service-utils
    url: https://github.com/konflux-ci/release-service-utils
    ref: cabbdbe2a69b9f80ded68fafb13f3bf02a808680  # main
    description: Base image with helper functions

  - name: release-service-collectors
    url: https://github.com/konflux-ci/release-service-collectors
    ref: e6646acd6dc660562e111a79d6ab412b82e16837  # main
    description: Collector scripts

catalog:
  repo: release-service-catalog
  url: https://github.com/konflux-ci/release-service-catalog
  schema_path: schema/dataKeys.json
  environments:
    development:
      branch: development
      ref: 70d113899e905673d7b067f63774fab176c55151  # development
    staging:
      branch: staging
      ref: 6cc550aec4d84e324f48e50cf4de14f1e43d048a  # staging
    production:
      branch: production
      ref: 3cc97973adc6711bc3d0d50ceba3648017c4349b  # production

docs:
  - name: releasing
    url: https://konflux-ci.dev/docs/releasing/

  - name: release-service-architecture
    url: https://konflux-ci.dev/architecture/core/release-service/

  - name: internal-services-architecture
    url: https://konflux-ci.dev/architecture/add-ons/internal-services/

  - name: tekton-pipelines
    url: https://tekton.dev/docs/pipelines/pipelines/

  - name: tekton-tasks
    url: https://tekton.dev/docs/pipelines/tasks/
