---
repos:
  - name: release-service
    url: https://github.com/konflux-ci/release-service
    ref: 10ecd5a39c9c6100b0dd51bf842a6ec839030129  # main
    description: Operator

  - name: internal-services
    url: https://github.com/konflux-ci/internal-services
    ref: 13be27e470d79fbea583909cffec24c1340f9c3c  # main
    description: Internal cluster controller

  - name: release-service-utils
    url: https://github.com/konflux-ci/release-service-utils
    ref: d9ec0be0b897e1e1f142a1ca8caffd26315a5e2f  # main
    description: Base image with helper functions

  - name: release-service-collectors
    url: https://github.com/konflux-ci/release-service-collectors
    ref: e6646acd6dc660562e111a79d6ab412b82e16837  # main
    description: Collector scripts

catalog:
  repo: release-service-catalog
  url: https://github.com/konflux-ci/release-service-catalog
  schema_path: schema/dataKeys.json
  environments:
    development:
      branch: development
      ref: bd0af1295a67d51bc2740bc9324690eb0e1e9b2e  # development
    staging:
      branch: staging
      ref: 56c749d703676d2cafce9ba20f0d9aff07893b19  # staging
    production:
      branch: production
      ref: 47e6ae585136381673fd5d7f7a773dd4ed471b33  # production

docs:
  - name: releasing
    url: https://konflux-ci.dev/docs/releasing/

  - name: release-service-architecture
    url: https://konflux-ci.dev/architecture/core/release-service/

  - name: internal-services-architecture
    url: https://konflux-ci.dev/architecture/add-ons/internal-services/

  - name: tekton-pipelines
    url: https://tekton.dev/docs/pipelines/pipelines/

  - name: tekton-tasks
    url: https://tekton.dev/docs/pipelines/tasks/
