---
repos:
  - name: release-service
    url: https://github.com/konflux-ci/release-service
    ref: 1f69a1c9e79b978f15ebf605f852d9a397a4d849  # main
    description: Operator

  - name: internal-services
    url: https://github.com/konflux-ci/internal-services
    ref: 9d679188b8b5d4e08b7a59998537b8850ac669a8  # main
    description: Internal cluster controller

  - name: release-service-utils
    url: https://github.com/konflux-ci/release-service-utils
    ref: f06636310d0799475f94af367a9b47ccb1d466c3  # main
    description: Base image with helper functions

  - name: release-service-collectors
    url: https://github.com/konflux-ci/release-service-collectors
    ref: e6646acd6dc660562e111a79d6ab412b82e16837  # main
    description: Collector scripts

catalog:
  repo: release-service-catalog
  url: https://github.com/konflux-ci/release-service-catalog
  schema_path: schema/dataKeys.json
  environments:
    development:
      branch: development
      ref: acbaf0738b24edf5947e9f66fa42cb905a77f00b  # development
    staging:
      branch: staging
      ref: d4752b9048ed2fc03331d802897a23f699b2303c  # staging
    production:
      branch: production
      ref: 38dd9aab24c3c024b4e582d45508fef60fc221dd  # production

docs:
  - name: releasing
    url: https://konflux-ci.dev/docs/releasing/

  - name: release-service-architecture
    url: https://konflux-ci.dev/architecture/core/release-service/

  - name: internal-services-architecture
    url: https://konflux-ci.dev/architecture/add-ons/internal-services/

  - name: tekton-pipelines
    url: https://tekton.dev/docs/pipelines/pipelines/

  - name: tekton-tasks
    url: https://tekton.dev/docs/pipelines/tasks/
